/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Behavioral_rec.java
 *
 * Created on Feb 7, 2013, 11:25:22 AM
 */

/**
 *
 * @author GIHANZ
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.*;
import java.awt.print.*;

public class Behavioral_rec extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /** Creates new form Behavioral_rec */
    public Behavioral_rec(String pass_id) {

        initComponents();
        conn=mysqlconnect.ConnecrDb();
        setIcon();
        Update_table(pass_id);
        header(pass_id);
    }

    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    private void Update_table(String pass_id) {
        try{
            String ID=pass_id;

            String sql="select * from Behavioralrecords where elephantid='"+ID+" ' ";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Table_Behavioral.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }

    private void header(String pass_id){

        try{
            String ID=pass_id;
            String sql="select * from Elephantinfo where elephantid='"+ID+"' ";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("elephantname");
                txt_name.setText(add1);
            }
        }catch(Exception e){

        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Behavioral = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_No = new javax.swing.JTextField();
        txt_Elephantid = new javax.swing.JTextField();
        txt_Elephantname = new javax.swing.JTextField();
        txt_Specific = new javax.swing.JTextField();
        txt_Remarks = new javax.swing.JTextField();
        txt_Date = new com.toedter.calendar.JDateChooser();
        Cmd_save = new javax.swing.JButton();
        Cmd_new = new javax.swing.JButton();
        Cmd_delete = new javax.swing.JButton();
        Cmd_update = new javax.swing.JButton();
        Cmd_back = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image = new javax.swing.JLabel();
        Cmd_attachimage = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        Cmd_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pinnawela Elephant Orphanage - Medical System [ Behavioral Records ]");

        Table_Behavioral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        Table_Behavioral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_BehavioralMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Behavioral);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 36));
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Pinnawala Elephant Orphanage ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 24));
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Behavioral Records of");

        txt_name.setFont(new java.awt.Font("Segoe UI Light", 1, 24));

        jLabel4.setText("No");

        jLabel5.setText("Elephant ID");

        jLabel6.setText("Elephant name");

        jLabel7.setText("Date");

        jLabel8.setText("Specific behaviour");

        jLabel9.setText("Remarks");

        txt_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NoActionPerformed(evt);
            }
        });

        txt_Date.setDateFormatString("yyyy-MM-dd");

        Cmd_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        Cmd_save.setText("Save");
        Cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_saveActionPerformed(evt);
            }
        });

        Cmd_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new.png"))); // NOI18N
        Cmd_new.setText("New");
        Cmd_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_newActionPerformed(evt);
            }
        });

        Cmd_delete.setText("Delete");
        Cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_deleteActionPerformed(evt);
            }
        });

        Cmd_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        Cmd_update.setText("Update");
        Cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_updateActionPerformed(evt);
            }
        });

        Cmd_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        Cmd_back.setText("Back");
        Cmd_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_backActionPerformed(evt);
            }
        });

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/behavioral_image.jpg"))); // NOI18N
        image.setText("jLabel10");
        image.setBounds(0, 0, 290, 190);
        jDesktopPane1.add(image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Cmd_attachimage.setText("Attach Image");
        Cmd_attachimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_attachimageActionPerformed(evt);
            }
        });

        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        Cmd_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        Cmd_print.setText("Print");
        Cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_Remarks)
                                            .addComponent(txt_Specific)
                                            .addComponent(txt_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_Elephantname)
                                            .addComponent(txt_Elephantid)
                                            .addComponent(txt_No, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cmd_attachimage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(path)))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cmd_save, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Cmd_new, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Cmd_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Cmd_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cmd_print, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(Cmd_back, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(596, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(218, 218, 218)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_name, 0, 0, Short.MAX_VALUE))
                                .addGap(43, 43, 43))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(Cmd_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Elephantid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Elephantname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Specific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Remarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cmd_delete)
                        .addComponent(Cmd_update))
                    .addComponent(Cmd_save)
                    .addComponent(Cmd_new)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cmd_attachimage)
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Cmd_print))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NoActionPerformed

    private void Table_BehavioralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_BehavioralMouseClicked

            int row=Table_Behavioral.getSelectedRow();
            String Table_click=(Table_Behavioral.getModel().getValueAt(row,0).toString());

        try{
            String sql="select image from behavioralrecords where no='"+Table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()){
                byte[]imagedata=rs.getBytes("image");
                format=new ImageIcon(imagedata);
                image.setIcon(format);
            }

        }catch(Exception e){
            e.printStackTrace();

        }



        try{
            
            String sql="select * from Behavioralrecords where no= '"+Table_click+" '";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()){
                String add1=rs.getString("no");
                txt_No.setText(add1);
                String add2=rs.getString("elephantid");
                txt_Elephantid.setText(add2);
                String add3=rs.getString("elephantname");
                txt_Elephantname.setText(add3);
                Date add4=rs.getDate("date");
                txt_Date.setDate(add4);
                String add5=rs.getString("specificbehaviour");
                txt_Specific.setText(add5);
                String add8=rs.getString("remarks");
                txt_Remarks.setText(add8);

            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_Table_BehavioralMouseClicked

    private void Cmd_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_newActionPerformed

        txt_No.setText("");
        txt_Elephantid.setText("");
        txt_Elephantname.setText("");
        txt_Date.setDate(null);
        txt_Specific.setText("");
        txt_Remarks.setText("");
    }//GEN-LAST:event_Cmd_newActionPerformed

    private void Cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_deleteActionPerformed

        int p=JOptionPane.showConfirmDialog(null, "Do you really want to delete ?","Delete",JOptionPane.YES_NO_OPTION);
        String pass_id = txt_Elephantid.getText();

     if(p==0){

        String sql="delete from Behavioralrecords where no =?";

        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_No.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Deleted");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Update_table(pass_id);
        }
    }//GEN-LAST:event_Cmd_deleteActionPerformed

    private void Cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_saveActionPerformed

        String pass_id=txt_Elephantid.getText();
        try{
            String sql="INSERT INTO Behavioralrecords (no,elephantid,elephantname,date,specificbehaviour,remarks,image) VALUES (?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);

            pst.setString(1, txt_No.getText());
            pst.setString(2, txt_Elephantid.getText());
            pst.setString(3, txt_Elephantname.getText());
            pst.setString(4, ((JTextField) txt_Date.getDateEditor().getUiComponent()).getText());
            pst.setString(5, txt_Specific.getText());
            pst.setString(6, txt_Remarks.getText());
            pst.setBytes(7, elephant_image);

            pst.execute();

            JOptionPane.showMessageDialog(null,"New Behavioral Record Saved");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        Update_table(pass_id);
    }//GEN-LAST:event_Cmd_saveActionPerformed

    private void Cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_updateActionPerformed

        String pass_id=txt_Elephantid.getText();
        try{
            String value1=txt_No.getText();
            String value2=txt_Elephantid.getText();
            String value3=txt_Elephantname.getText();
            String value4=((JTextField) txt_Date.getDateEditor().getUiComponent()).getText();
            String value5=txt_Specific.getText();
            String value6=txt_Remarks.getText();
            byte[] value7=elephant_image;

           String sql="update Behavioralrecords set no='"+value1+"', elephantid='"+value2+"',elephantname='"+value3+"',date='"+value4+"',specificbehaviour='"+value5+"',remarks='"+value6+"',image='"+value7+"' where no='"+value1+"' ";
           pst=conn.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(null,"Updated");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }

        Update_table(pass_id);
    }//GEN-LAST:event_Cmd_updateActionPerformed

    private void Cmd_attachimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_attachimageActionPerformed

        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();

        path.setText(filename);

        try{
            File image=new File(filename);
            FileInputStream fis=new FileInputStream(image);

            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf= new byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }

            elephant_image=bos.toByteArray();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_Cmd_attachimageActionPerformed

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed

    private void Cmd_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_backActionPerformed

        dispose();
}//GEN-LAST:event_Cmd_backActionPerformed

    private void Cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_printActionPerformed

        MessageFormat header=new MessageFormat("Elephant Medical System Batabase Report");
        MessageFormat footer=new MessageFormat("Page(0,number,integer)");

        try{

            Table_Behavioral.print(JTable.PrintMode.FIT_WIDTH,header,footer);

        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n",e.getMessage() );

        }
    }//GEN-LAST:event_Cmd_printActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {

            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(String pass_id) {
                new Behavioral_rec(pass_id).setVisible(true);
            }
            public void run() {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        });


        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Behavioral_rec.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Behavioral_rec.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Behavioral_rec.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Behavioral_rec.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cmd_attachimage;
    private javax.swing.JButton Cmd_back;
    private javax.swing.JButton Cmd_delete;
    private javax.swing.JButton Cmd_new;
    private javax.swing.JButton Cmd_print;
    private javax.swing.JButton Cmd_save;
    private javax.swing.JButton Cmd_update;
    private javax.swing.JTable Table_Behavioral;
    private javax.swing.JLabel image;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField path;
    private com.toedter.calendar.JDateChooser txt_Date;
    private javax.swing.JTextField txt_Elephantid;
    private javax.swing.JTextField txt_Elephantname;
    private javax.swing.JTextField txt_No;
    private javax.swing.JTextField txt_Remarks;
    private javax.swing.JTextField txt_Specific;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format=null;

    String filename=null;
    int s =0;
    byte[] elephant_image=null;

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
