/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Breeding_rec.java
 *
 * Created on Feb 7, 2013, 11:25:49 AM
 */

/**
 *
 * @author GIHANZ
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.awt.*;
import java.awt.event.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.*;
import java.awt.print.*;

public class Breeding_rec extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /** Creates new form Breeding_rec */
    public Breeding_rec(String pass_id) {

        initComponents();
        conn=mysqlconnect.ConnecrDb();
        setIcon();
        Update_table(pass_id);
        header(pass_id);
    }

    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    private void Update_table(String pass_id) {
        try{
            String ID=pass_id;

            String sql="select * from Breedingrecords where elephantid='"+ID+" ' ";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Table_Breeding.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }

    private void header(String pass_id){

        try{
            String ID=pass_id;
            String sql="select * from Elephantinfo where elephantid='"+ID+"' ";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("elephantname");
                txt_name.setText(add1);
            }
        }catch(Exception e){

        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Breeding = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_No = new javax.swing.JTextField();
        txt_Elephantid = new javax.swing.JTextField();
        txt_Elephantname = new javax.swing.JTextField();
        txt_Intercalving = new javax.swing.JTextField();
        txt_Mother = new javax.swing.JTextField();
        txt_Nameofkid = new javax.swing.JTextField();
        txt_Date = new com.toedter.calendar.JDateChooser();
        Cmd_save = new javax.swing.JButton();
        Cmd_new = new javax.swing.JButton();
        Cmd_delete = new javax.swing.JButton();
        Cmd_update = new javax.swing.JButton();
        txt_Puberty = new com.toedter.calendar.JDateChooser();
        txt_1st = new com.toedter.calendar.JDateChooser();
        txt_2nd = new com.toedter.calendar.JDateChooser();
        txt_Expected = new com.toedter.calendar.JDateChooser();
        txt_Calving = new com.toedter.calendar.JDateChooser();
        Cmd_back = new javax.swing.JButton();
        Cmd_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pinnawela Elephant Orphanage - Medical System [ Breeding Records ]");

        Table_Breeding.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        Table_Breeding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_BreedingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Breeding);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 36));
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Pinnawala Elephant Orphanage ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 24));
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Breeding Records of");

        txt_name.setFont(new java.awt.Font("Segoe UI Light", 1, 24));
        txt_name.setForeground(new java.awt.Color(0, 51, 51));

        jLabel4.setText("No");

        jLabel5.setText("Elephant ID");

        jLabel6.setText("Elephant name");

        jLabel7.setText("Date");

        jLabel8.setText("Puberty date");

        jLabel9.setText("1st mating");

        jLabel10.setText("2nd mating");

        jLabel11.setText("Expected calving date");

        jLabel12.setText("Calving date");

        jLabel13.setText("Intercalving interval");

        jLabel14.setText("Mother elephant age");

        jLabel15.setText("Name of kid");

        txt_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NoActionPerformed(evt);
            }
        });

        txt_Date.setDateFormatString("yyyy-MM-dd");

        Cmd_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        Cmd_save.setText("Save");
        Cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_saveActionPerformed(evt);
            }
        });

        Cmd_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new.png"))); // NOI18N
        Cmd_new.setText("New");
        Cmd_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_newActionPerformed(evt);
            }
        });

        Cmd_delete.setText("Delete");
        Cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_deleteActionPerformed(evt);
            }
        });

        Cmd_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        Cmd_update.setText("Update");
        Cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_updateActionPerformed(evt);
            }
        });

        txt_Puberty.setDateFormatString("yyyy-MM-dd");

        txt_1st.setDateFormatString("yyyy-MM-dd");

        txt_2nd.setDateFormatString("yyyy-MM-dd");

        txt_Expected.setDateFormatString("yyyy-MM-dd");

        txt_Calving.setDateFormatString("yyyy-MM-dd");

        Cmd_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        Cmd_back.setText("Back");
        Cmd_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_backActionPerformed(evt);
            }
        });

        Cmd_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        Cmd_print.setText("Print");
        Cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_No, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txt_Elephantid)
                            .addComponent(txt_Elephantname)
                            .addComponent(txt_Intercalving)
                            .addComponent(txt_Mother)
                            .addComponent(txt_Nameofkid)
                            .addComponent(txt_Puberty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_1st, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_2nd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Expected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Calving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Cmd_save, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(Cmd_new, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Cmd_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Cmd_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cmd_print, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Cmd_back, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(582, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)))
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Cmd_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_Elephantid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Elephantname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_Puberty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(txt_1st, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_2nd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_Expected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(txt_Calving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Intercalving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Mother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Nameofkid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cmd_new)
                    .addComponent(Cmd_delete)
                    .addComponent(Cmd_update)
                    .addComponent(Cmd_save)
                    .addComponent(Cmd_print))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NoActionPerformed

    private void Table_BreedingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_BreedingMouseClicked

        try{
            int row=Table_Breeding.getSelectedRow();
            String Table_click=(Table_Breeding.getModel().getValueAt(row,0).toString());
            String sql="select * from  Breedingrecords where no= '"+Table_click+" '";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()){
                String add1=rs.getString("no");
                txt_No.setText(add1);
                String add2=rs.getString("elephantid");
                txt_Elephantid.setText(add2);
                String add3=rs.getString("elephantname");
                txt_Elephantname.setText(add3);
                Date add4=rs.getDate("date");
                txt_Date.setDate(add4);
                Date add5=rs.getDate("pubertydate");
                txt_Puberty.setDate(add5);
                Date add6=rs.getDate("1_mating");
                txt_1st.setDate(add6);
                Date add7=rs.getDate("2_mating");
                txt_2nd.setDate(add7);
                Date add8=rs.getDate("expectedcalvingdate");
                txt_Expected.setDate(add8);
                Date add9=rs.getDate("calvingdate");
                txt_Calving.setDate(add9);
                String add10=rs.getString("intercalvinginterval");
                txt_Intercalving.setText(add10);
                String add11=rs.getString("mothersage");
                txt_Mother.setText(add11);
                String add12=rs.getString("nameofkid");
                txt_Nameofkid.setText(add12);

            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_Table_BreedingMouseClicked

    private void Cmd_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_newActionPerformed
        
        txt_No.setText("");
        txt_Elephantid.setText("");
        txt_Elephantname.setText("");
        txt_Date.setDate(null);
        txt_Puberty.setDate(null);
        txt_1st.setDate(null);
        txt_2nd.setDate(null);
        txt_Expected.setDate(null);
        txt_Calving.setDate(null);
        txt_Intercalving.setText("");
        txt_Mother.setText("");
        txt_Nameofkid.setText("");
    }//GEN-LAST:event_Cmd_newActionPerformed

    private void Cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_deleteActionPerformed

           int p=JOptionPane.showConfirmDialog(null, "Do you really want to delete ?","Delete",JOptionPane.YES_NO_OPTION);
           String pass_id = txt_Elephantid.getText();

     if(p==0){

        String sql="delete from Breedingrecords where no =?";

        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_No.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Selected Breeding Record Deleted");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Update_table(pass_id);
        }
    }//GEN-LAST:event_Cmd_deleteActionPerformed

    private void Cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_saveActionPerformed

        String pass_id=txt_Elephantid.getText();
        try{
            String sql="INSERT INTO Breedingrecords (no,elephantid,elephantname,date,pubertydate,1_mating,2_mating,expectedcalvingdate,calvingdate,intercalvinginterval,mothersage,nameofkid) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);

            pst.setString(1, txt_No.getText());
            pst.setString(2, txt_Elephantid.getText());
            pst.setString(3, txt_Elephantname.getText());
            pst.setString(4, ((JTextField) txt_Date.getDateEditor().getUiComponent()).getText());
            pst.setString(5, ((JTextField) txt_Puberty.getDateEditor().getUiComponent()).getText());
            pst.setString(6, ((JTextField) txt_1st.getDateEditor().getUiComponent()).getText());
            pst.setString(7, ((JTextField) txt_2nd.getDateEditor().getUiComponent()).getText());
            pst.setString(8, ((JTextField) txt_Expected.getDateEditor().getUiComponent()).getText());
            pst.setString(9, ((JTextField) txt_Calving.getDateEditor().getUiComponent()).getText());
            pst.setString(10, txt_Intercalving.getText());
            pst.setString(11, txt_Mother.getText());
            pst.setString(12, txt_Nameofkid.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null,"New Breeding Record Saved");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        Update_table(pass_id);

    }//GEN-LAST:event_Cmd_saveActionPerformed

    private void Cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_updateActionPerformed

        String pass_id=txt_Elephantid.getText();
        try{
            String value1=txt_No.getText();
            String value2=txt_Elephantid.getText();
            String value3=txt_Elephantname.getText();
            String value4=((JTextField) txt_Date.getDateEditor().getUiComponent()).getText();
            String value5=((JTextField) txt_Puberty.getDateEditor().getUiComponent()).getText();
            String value6=((JTextField) txt_1st.getDateEditor().getUiComponent()).getText();
            String value7=((JTextField) txt_2nd.getDateEditor().getUiComponent()).getText();
            String value8=((JTextField) txt_Expected.getDateEditor().getUiComponent()).getText();
            String value9=((JTextField) txt_Calving.getDateEditor().getUiComponent()).getText();
            String value10=txt_Intercalving.getText();
            String value11=txt_Mother.getText();
            String value12=txt_Nameofkid.getText();

           String sql="update Breedingrecords set no='"+value1+"', elephantid='"+value2+"',elephantname='"+value3+"',date='"+value4+"',pubertydate='"+value5+"',1_mating='"+value6+"',2_mating='"+value7+"',expectedcalvingdate='"+value8+"',calvingdate='"+value9+"',intercalvinginterval='"+value10+"',mothersage='"+value11+"',nameofkid='"+value12+"' where no='"+value1+"' ";
           pst=conn.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(null,"Updated");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }

        Update_table(pass_id);
    }//GEN-LAST:event_Cmd_updateActionPerformed

    private void Cmd_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_backActionPerformed

            dispose();
    }//GEN-LAST:event_Cmd_backActionPerformed

    private void Cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_printActionPerformed

        MessageFormat header=new MessageFormat("Elephant Medical System Batabase Report");
        MessageFormat footer=new MessageFormat("Page(0,number,integer)");

        try{

            Table_Breeding.print(JTable.PrintMode.FIT_WIDTH,header,footer);

        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n",e.getMessage() );

        }
    }//GEN-LAST:event_Cmd_printActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {

            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(String pass_id) {
                new Breeding_rec(pass_id).setVisible(true);
            }
            public void run() {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        });

        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Breeding_rec.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Breeding_rec.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Breeding_rec.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Breeding_rec.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cmd_back;
    private javax.swing.JButton Cmd_delete;
    private javax.swing.JButton Cmd_new;
    private javax.swing.JButton Cmd_print;
    private javax.swing.JButton Cmd_save;
    private javax.swing.JButton Cmd_update;
    private javax.swing.JTable Table_Breeding;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser txt_1st;
    private com.toedter.calendar.JDateChooser txt_2nd;
    private com.toedter.calendar.JDateChooser txt_Calving;
    private com.toedter.calendar.JDateChooser txt_Date;
    private javax.swing.JTextField txt_Elephantid;
    private javax.swing.JTextField txt_Elephantname;
    private com.toedter.calendar.JDateChooser txt_Expected;
    private javax.swing.JTextField txt_Intercalving;
    private javax.swing.JTextField txt_Mother;
    private javax.swing.JTextField txt_Nameofkid;
    private javax.swing.JTextField txt_No;
    private com.toedter.calendar.JDateChooser txt_Puberty;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
