/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Clinical_rec.java
 *
 * Created on Feb 7, 2013, 11:24:32 AM
 */

/**
 *
 * @author GIHANZ
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.awt.*;
import java.awt.event.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.*;
import java.awt.print.*;

public class Clinical_rec extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /** Creates new form Clinical_rec */
    public Clinical_rec(String pass_id) {

        initComponents();
        conn=mysqlconnect.ConnecrDb();
        setIcon();
        Update_table(pass_id);
        header(pass_id);

    }

    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }


    private void Update_table(String pass_id) {
        try{
            String ID=pass_id;
            String sql="select * from Clinicalrecords where elephantid='"+ID+"' ";
           
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Table_Clinical.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }

    private void header(String pass_id){

        try{
            String ID=pass_id;
            String sql="select * from Elephantinfo where elephantid='"+ID+"' ";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("elephantname");
                txt_name.setText(add1);
            }
        }catch(Exception e){

        }

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Clinical = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_No = new javax.swing.JTextField();
        txt_Elephantid = new javax.swing.JTextField();
        txt_Elephantname = new javax.swing.JTextField();
        txt_Age = new javax.swing.JTextField();
        txt_Complain = new javax.swing.JTextField();
        txt_Diagnosis = new javax.swing.JTextField();
        txt_Test = new javax.swing.JTextField();
        txt_Clinical = new javax.swing.JTextField();
        txt_External = new javax.swing.JTextField();
        txt_Treatments = new javax.swing.JTextField();
        txt_Remarks = new javax.swing.JTextField();
        txt_Date = new com.toedter.calendar.JDateChooser();
        Cmd_save = new javax.swing.JButton();
        Cmd_new = new javax.swing.JButton();
        Cmd_delete = new javax.swing.JButton();
        Cmd_update = new javax.swing.JButton();
        Cmd_back = new javax.swing.JButton();
        Cmd_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pinnawela Elephant Orphanage - Medical System [ Clinical Records ]");

        Table_Clinical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        Table_Clinical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ClinicalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Clinical);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel1.setMinimumSize(new java.awt.Dimension(130, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 36));
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Pinnawala Elephant Orphanage ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 24));
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Clinical Records of");

        txt_name.setFont(new java.awt.Font("Segoe UI Light", 1, 24));
        txt_name.setForeground(new java.awt.Color(0, 51, 51));

        jLabel5.setText("No");

        jLabel6.setText("Elephant ID");

        jLabel7.setText("Elephant name");

        jLabel8.setText("Date");

        jLabel9.setText("Age");

        jLabel10.setText("Complain/history");

        jLabel11.setText("Diagnosis");

        jLabel12.setText("Test done");

        jLabel13.setText("Clinical examinations");

        jLabel14.setText("External observations");

        jLabel15.setText("Treatments");

        jLabel16.setText("Remarks");

        txt_Elephantname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ElephantnameActionPerformed(evt);
            }
        });

        txt_Date.setDateFormatString("yyyy-MM-dd");

        Cmd_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        Cmd_save.setText("Save");
        Cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_saveActionPerformed(evt);
            }
        });

        Cmd_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new.png"))); // NOI18N
        Cmd_new.setText("New");
        Cmd_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_newActionPerformed(evt);
            }
        });

        Cmd_delete.setText("Delete");
        Cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_deleteActionPerformed(evt);
            }
        });

        Cmd_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        Cmd_update.setText("Update");
        Cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_updateActionPerformed(evt);
            }
        });

        Cmd_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        Cmd_back.setText("Back");
        Cmd_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_backActionPerformed(evt);
            }
        });

        Cmd_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        Cmd_print.setText("Print");
        Cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Cmd_back, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(379, 379, 379)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(577, 577, 577)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_Elephantname)
                                    .addComponent(txt_Elephantid)
                                    .addComponent(txt_Age)
                                    .addComponent(txt_Complain)
                                    .addComponent(txt_Diagnosis)
                                    .addComponent(txt_Test)
                                    .addComponent(txt_Clinical)
                                    .addComponent(txt_External)
                                    .addComponent(txt_Treatments)
                                    .addComponent(txt_Remarks)
                                    .addComponent(txt_No, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cmd_save, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cmd_new, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cmd_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cmd_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                                .addComponent(Cmd_print, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jScrollPane1))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Cmd_back)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Elephantid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_Elephantname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_Complain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_Diagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_Test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_Clinical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_External, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_Treatments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_Remarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cmd_delete)
                        .addComponent(Cmd_update))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Cmd_save, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(Cmd_new, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Cmd_print))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ElephantnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ElephantnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ElephantnameActionPerformed

    private void Table_ClinicalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ClinicalMouseClicked

        try{
            int row=Table_Clinical.getSelectedRow();
            String Table_click=(Table_Clinical.getModel().getValueAt(row,0).toString());
            String sql="select * from Clinicalrecords where no= '"+Table_click+" '";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()){
                String add1=rs.getString("no");
                txt_No.setText(add1);
                String add2=rs.getString("elephantid");
                txt_Elephantid.setText(add2);
                String add3=rs.getString("elephantname");
                txt_Elephantname.setText(add3);
                Date add4=rs.getDate("date");
                txt_Date.setDate(add4);
                String add5=rs.getString("elephantage");
                txt_Age.setText(add5);
                String add6=rs.getString("complainhistory");
                txt_Complain.setText(add6);
                String add7=rs.getString("diagnosis");
                txt_Diagnosis.setText(add7);
                String add8=rs.getString("testdone");
                txt_Test.setText(add8);
                String add9=rs.getString("clinicalexamination");
                txt_Clinical.setText(add9);
                String add10=rs.getString("externalobservations");
                txt_External.setText(add10);
                String add11=rs.getString("treatments");
                txt_Treatments.setText(add11);
                String add12=rs.getString("remarks");
                txt_Remarks.setText(add12);

            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_Table_ClinicalMouseClicked

    private void Cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_deleteActionPerformed

        int p=JOptionPane.showConfirmDialog(null, "Do you really want to delete ?","Delete",JOptionPane.YES_NO_OPTION);
        String pass_id = txt_Elephantid.getText();

     if(p==0){

        String sql="delete from Clinicalrecords where no =?";

        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_No.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Deleted");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Update_table(pass_id);
        }
    }//GEN-LAST:event_Cmd_deleteActionPerformed

    private void Cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_updateActionPerformed
        
        String pass_id=txt_Elephantid.getText();
        try{
            String value1=txt_No.getText();
            String value2=txt_Elephantid.getText();
            String value3=txt_Elephantname.getText();
            String value4=((JTextField) txt_Date.getDateEditor().getUiComponent()).getText();
            String value5=txt_Age.getText();
            String value6=txt_Complain.getText();
            String value7=txt_Diagnosis.getText();
            String value8=txt_Test.getText();
            String value9=txt_Clinical.getText();
            String value10=txt_External.getText();
            String value11=txt_Treatments.getText();
            String value12=txt_Remarks.getText();

           String sql="update Clinicalrecords set no='"+value1+"', elephantid='"+value2+"',elephantname='"+value3+"',date='"+value4+"',elephantage='"+value5+"',complainhistory='"+value6+"',diagnosis='"+value7+"',testdone='"+value8+"',clinicalexamination='"+value9+"',externalobservations='"+value10+"',treatments='"+value11+"',remarks='"+value12+"' where no='"+value1+"' ";
           pst=conn.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(null,"Updated");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
        
        Update_table(pass_id);
    }//GEN-LAST:event_Cmd_updateActionPerformed

    private void Cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_saveActionPerformed

        String pass_id=txt_Elephantid.getText();
        try{
            String sql="INSERT INTO Clinicalrecords (no,elephantid,elephantname,date,elephantage,complainhistory,diagnosis,testdone,clinicalexamination,externalobservations,treatments,remarks) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);

            pst.setString(1, txt_No.getText());
            pst.setString(2, txt_Elephantid.getText());
            pst.setString(3, txt_Elephantname.getText());
            pst.setString(4, ((JTextField) txt_Date.getDateEditor().getUiComponent()).getText());
            pst.setString(5, txt_Age.getText());
            pst.setString(6, txt_Complain.getText());
            pst.setString(7, txt_Diagnosis.getText());
            pst.setString(8, txt_Test.getText());
            pst.setString(9, txt_Clinical.getText());
            pst.setString(10, txt_External.getText());
            pst.setString(11, txt_Treatments.getText());
            pst.setString(12, txt_Remarks.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null,"New Clinical Record Saved");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        Update_table(pass_id);
    }//GEN-LAST:event_Cmd_saveActionPerformed

    private void Cmd_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_newActionPerformed
        
        txt_No.setText("");
        txt_Elephantid.setText("");
        txt_Elephantname.setText("");
        txt_Date.setDate(null);
        txt_Age.setText("");
        txt_Complain.setText("");
        txt_Diagnosis.setText("");
        txt_Test.setText("");
        txt_Clinical.setText("");
        txt_External.setText("");
        txt_Treatments.setText("");
        txt_Remarks.setText("");
   
    }//GEN-LAST:event_Cmd_newActionPerformed

    private void Cmd_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_backActionPerformed

            dispose();
    }//GEN-LAST:event_Cmd_backActionPerformed

    private void Cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_printActionPerformed

        MessageFormat header=new MessageFormat("Elephant Medical System Batabase Report");
        MessageFormat footer=new MessageFormat("Page(0,number,integer)");

        try{

            Table_Clinical.print(JTable.PrintMode.FIT_WIDTH,header,footer);

        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n",e.getMessage() );

        }
    }//GEN-LAST:event_Cmd_printActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {

            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(String pass_id) {
                new Clinical_rec(pass_id).setVisible(true);
            }

            public void run() {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        });


        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Clinical_rec.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Clinical_rec.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Clinical_rec.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Clinical_rec.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cmd_back;
    private javax.swing.JButton Cmd_delete;
    private javax.swing.JButton Cmd_new;
    private javax.swing.JButton Cmd_print;
    private javax.swing.JButton Cmd_save;
    private javax.swing.JButton Cmd_update;
    private javax.swing.JTable Table_Clinical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Age;
    private javax.swing.JTextField txt_Clinical;
    private javax.swing.JTextField txt_Complain;
    private com.toedter.calendar.JDateChooser txt_Date;
    private javax.swing.JTextField txt_Diagnosis;
    private javax.swing.JTextField txt_Elephantid;
    private javax.swing.JTextField txt_Elephantname;
    private javax.swing.JTextField txt_External;
    private javax.swing.JTextField txt_No;
    private javax.swing.JTextField txt_Remarks;
    private javax.swing.JTextField txt_Test;
    private javax.swing.JTextField txt_Treatments;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
